<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageVersion>0.0.5</PackageVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>


  <PropertyGroup>
    <AssemblyTitle>HCMUtils</AssemblyTitle>
    <Copyright>Bundesnetzagentur ©  2026</Copyright>
    <AssemblyVersion>0.0.5</AssemblyVersion>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
