namespace HCMUtils.MultiCalc;

using HCMUtils.Types;

public record PointToPointInput(
    int Mode,
    (double Long, double Lat) TxCoordinates,
    int? TxSiteHeight,
    (string Horizontal, string Vertical) TxAntennaType,
    double TxAzimuth,
    double TxElevation,
    int TxAntennaHeight,
    double TxPower,
    GainType TxGainType,
    double TxFrequency,
    bool ChannelOccupation,
    Temperature? SeaTemperature,
    double? DistanceOverSea,
    int TxServiceAreaRadius,
    (double Long, double Lat) RxCoordinates,
    int? RxSiteHeight,
    int RxAntennaHeight,
    Country TxCountry,
    Country RxCountry,
    double? PermissibleFieldStrength,
    double RxFrequency,
    string TxEmissionDesignation,
    string RxEmissionDesignation,
    (string Horizontal, string Vertical) RxAntennaType,
    double RxAzimuth,
    double RxElevation,
    GainType RxGainType,
    double RxGain,
    double DepolarizationLoss,
    int? FrequencyDifferenceCorrectionFactor,
    int RxServiceAreaRadius
) : Input(
        Mode,
        TxCoordinates,
        TxSiteHeight,
        TxAntennaType,
        TxAzimuth,
        TxElevation,
        TxAntennaHeight,
        TxPower,
        TxGainType,
        TxFrequency,
        ChannelOccupation,
        SeaTemperature,
        DistanceOverSea,
        TxServiceAreaRadius,
        TxCountry,
        PermissibleFieldStrength,
        TxEmissionDesignation
);
