namespace HCMUtils.Types;

public record BuildLegacyStringPointToPointInput(
    (double Lat, double Long) TxCoordinates,
    (double Lat, double Long) RxCoordinates,
    int? TxSiteHeight,
    int? RxSiteHeight,
    (string Horizontal, string Vertical) TxAntennaType,
    double TxAzimuth,
    double TxElevation,
    int TxAntennaHeight,
    int RxAntennaHeight,
    GainType TxGainType,
    double TxPower,
    double TxFrequency,
    bool ChannelOccupation,
    Temperature? SeaTemperature,
    int TxServiceAreaRadius,
    int RxServiceAreaRadius,
    double? DistanceOverSea,
    double RxFrequency,
    string RxEmissionDesignation,
    string TxEmissionDesignation,
    (string Horizontal, string Vertical) RxAntennaType,
    double RxAzimuth,
    double RxElevation,
    GainType RxGainType,
    double RxGain,
    double DepolarizationLoss,
    double? PermissibleFieldStrength,
    int? FrequencyDifferenceCorrectionFactor,
    Country RxCountry,
    Country TxCountry,
    string TopoPath,
    string BorderPath,
    string MorphoPath,
    string? DebugOutputPath

);
