<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <PropertyGroup>
    <AssemblyTitle>HCMUtils</AssemblyTitle>
    <Copyright>Bundesnetzagentur ©  2026</Copyright>
    <AssemblyVersion>0.0.1</AssemblyVersion>
  </PropertyGroup>

</Project>
