name: check
on:
  push:
    branches:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
      - run: dotnet tool update -g docfx
      - run: docfx docfx.json
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
      - run: dotnet test --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml --coverage-settings CodeCoverage.runsettings
      - uses: 5monkeys/cobertura-action@master
        continue-on-error: true
        with:
          fail_below_threshold: true
          path: tests/HCMUtils.Tests/bin/Debug/net10.0/TestResults/coverage.cobertura.xml
          skip_covered: false
          minimum_coverage: 75
          report_name: coverage
  verify-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
      - run: dotnet format --verify-no-changes
